// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Edges struct {
	Node *Node `json:"Node"`
}

type Node struct {
	Address string  `json:"Address"`
	Name    string  `json:"Name"`
	Stats   *Stats  `json:"Stats"`
	Symbol  *string `json:"Symbol"`
}

type Stats struct {
	TotalSales int     `json:"TotalSales"`
	Average    float64 `json:"Average"`
	Ceiling    float64 `json:"Ceiling"`
	Floor      float64 `json:"Floor"`
	Volume     float64 `json:"Volume"`
}

type TrendingCollections struct {
	Edges []*Edges `json:"Edges"`
}
